apiVersion: v1
kind: Service
metadata:
  name: {{ include "swamibot.fullname" . }}
  labels:
    {{- include "swamibot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "swamibot.selectorLabels" . | nindent 4 }}
